config/routes.rb
Rails.application.routes.draw do
 
  resources :applications do
    resources :chats do
      resources :messages
    end
  end
  

  resources :applications 
  resources :chats 
  resources :messages
  
 


  root "applications#index"
  get "/applications/:application_id/chats/:chat_id/messages/search", to: "messages#search_messages"
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :chats

  has_secure_token

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  belongs_to :application

end

app/models/message.rb
class Message < ApplicationRecord
 belongs_to :chat

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: %i[ show edit update destroy ]

  
  # GET /applications or /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1 or /applications/1.json
  def show
    @application = Application.find(params[:id])

    # creates a new comment object with atricle_id already initialized
    @chat = @application.chats.build
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications or /applications.json
  def create
    @app = Application.new(application_params)
    if @app.save
      render json: {msg: "Application created successfully", token: @app[:token]}, status: :ok
    else
      render json: {msg: "Application creation failed. Please double check the data provided"}, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to application_url(@application), notice: "Application was successfully updated." }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def application_params
      params.require(:application).permit(:name)
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[ show edit update destroy ]

  
  # GET /chats or /chats.json
  def index
    @application = Application.find(params[:application_id])
    @chats=Chat.where(application_id: @application.id).all
    
  end

  # GET /chats/1 or /chats/1.json
  def show
    
      @chat = Chats.find(params[:id])
  
  end

  # GET /chats/new
  def new
    @chat = Chat.new

  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats or /chats.json
  def create
    @application = Application.find(params[:application_id])
    @application.chat_count = @application.chats.size
    @application.update(chat_count:@application.chats.size )
    chat = @application.chats.create
    chat.number = @application.chats.size+1

    #application.chat_count = application.chats.size 
    #redirect_to application_path(application)
    #chat = chat_params.merge({number: chat_number, application_id: @application.id})
    render json: {msg: "Chat created successfully", number: chat.number}, status: :created


  end

  # PATCH/PUT /chats/1 or /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to chat_url(@chat), notice: "Chat was successfully updated." }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1 or /chats/1.json
  def destroy
    Chat.destroy(@chat.id)
    render json: {msg: "Chat destroyed successfully"}, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat)
    end


   
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    
      @messages = Message.all
    

  end
  


  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @chat = Chat.find(params[:chat_id])
    @chat.message_count = @chat.messagess.size
    @chat.update(cmessage_count:@chat.messagess.size )
    chat = @chat.messages.create
    @message.update(message.number = @chat.messages.size+1)

    render json: {msg: "message created successfully", number: message.number}, status: :created
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:chat_id,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/applications/_application.html.erb
<div id="<%= dom_id application %>">
  

  <p>
    <strong>Name:</strong>
    <%= application.name %>
  </p>

  <p>
    <strong>Chat count:</strong>
    <%= application.chat_count %>
  </p>

</div>

app/views/applications/_form.html.erb
<%= form_with(model: application) do |form| %>
  <% if application.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
        <% application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render "form", application: @application %>

<br>

<div>
  <%= link_to "Show this application", @application %> |
  <%= link_to "Back to applications", applications_path %>
</div>

app/views/applications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Applications</h1>

<div id="applications">
  <% @applications.each do |application| %>

       application name : <%= application.name %>
       <br>
       chats in application : <%= application.chats.count %>
    
    <p>
      <%= link_to "Show this application", application %>
    </p>
  <% end %>
</div>

<%= link_to "New application", new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render "form", application: @application %>

<br>

<div>
  <%= link_to "Back to applications", applications_path %>
</div>

app/views/applications/show.html.erb
<p style="color: green"><%= notice %></p>

<h2>chats</h2>
<% @application.chats.each do |chat| %>
  <p>
    <strong>Chat number:</strong>
    <%= chat.number %>
  </p>

  <% chat.messages.each do |message| %>
     <%= message.body %>
  <% end %>

<% end %>

<h2>Add a chat:</h2>
<%= form_with model: [ @application, @application.chats.build ] do |form| %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<div>
  <%= link_to "Edit this application", edit_application_path(@application) %> |
  <%= link_to "Back to applications", applications_path %>

  <%= button_to "Destroy this application", @application, method: :delete %>
</div>

app/views/chats/_chat.html.erb
<div id="<%= dom_id chat %>">
  <p>
    <strong>Number:</strong>
    <%= chat.number %>
  </p>

  

</div>

app/views/chats/_form.html.erb
<%= form_with(model: chat) do |form| %>
  <% if chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

 
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Show this chat", @chat %> |
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chats</h1>

<div id="chats">
  <% @chats.each do |chat| %>
    <%= render chat %>
    <p>
      <%= link_to "Show this chat", chat %>
    </p>
  <% end %>
</div>

<%= link_to "New chat", new_chat_path %>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render "form", chat: @chat %>

<br>

<div>
  <%= link_to "Back to chats", chats_path %>
</div>

app/views/chats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chat %>

<div>
  <%= link_to "Edit this chat", edit_chat_path(@chat) %> |
  <%= link_to "Back to chats", chats_path %>

  <%= button_to "Destroy this chat", @chat, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field:body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>body:</strong>
    <%= message.body %>
  </p>

</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= message.body %>
    
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>